apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-hackathon-medicos-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiap-hackathon-medicos-api
  template:
    metadata:
      labels:
        app: fiap-hackathon-medicos-api
    spec:
      containers:
        - name: fiap-hackathon-medicos-api
          image: seu-registro/fiap-hackathon-medicos-api:latest
          ports:
            - containerPort: 5011
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "5011"
