services:
  
  # .API MEDICOS
  medicos-api:
    build:
      context: .
      dockerfile: src/Medicos/Fiap.Hackathon.Medicos.API/Dockerfile
    container_name: medico_app
    restart: always
    ports:
      - "5011:5011"
    #environment:
     # ASPNETCORE_ENVIRONMENT: "Docker" 
    networks:
      - techchallenge-hackathon
 
networks:
  techchallenge-hackathon:
    external: true