services:
  
  # .API MEDICOS
  medicos-api:
    image: tatianacardoso/fiap-medicos-api:1
    build:
      context: .
      dockerfile: src/Medicos/Fiap.Hackathon.Medicos.API/Dockerfile
    container_name: fiap-medico_app
    restart: always        
    #environment:
     # ASPNETCORE_ENVIRONMENT: "Docker" 

 
