apiVersion: v1
kind: Secret
metadata:
  name: hackathon-medicos-secret
type: Opaque
data:
  MONGO_CONNECTION_STRING: bW9uZ29kYjovL2ZpYXA6ZmlhcDEyMzQ1NkBzZXJ2aWNlLW1vbmdvLWRiOjI3MDE3L2FkbWlu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-medicos
  labels:
    app: hackathon-medicos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hackathon-medicos
  template:
    metadata:
      labels:
        app: hackathon-medicos
    spec:
      containers:
        - name: container-hackathon-medicos
          image: tatianacardoso/fiap-medicos-api:6
          ports:
            - containerPort: 5011         
          env:
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: hackathon-medicos-secret
                  key: MONGO_CONNECTION_STRING            
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: service-hackathon-medicos
  labels:
    app: hackathon-medicos
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5011
      nodePort: 31001
  selector:
    app: hackathon-medicos